name: Build and Deploy
on:
    push:
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "14"
            - name: Install Dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: FTP Deploy
              uses: SamKirkland/FTP-Deploy-Action@4.1.0
              with:
                  server: ftpcluster.loopia.se
                  username: gnista
                  password: ${{ secrets.ftp_password }}
                  server-dir: public_html/
                  local-dir: dist/
